---
apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "imparsable"
  labels:
    io.cilium/mtls-enabled: "true"
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "imparsable-api"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
spec: {}
