apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: registry-secret
spec:
  hostAPI: "{{ .Values.parameters.infisical.host }}"
  resyncInterval: 60
  authentication:
    universalAuth:
      credentialsRef:
        secretName: "{{ .Values.parameters.infisical.auth_secret_name }}"
        secretNamespace: "{{ .Values.parameters.infisical.auth_secret_namespace }}"
      secretsScope:
        projectSlug: "{{ .Values.parameters.registry.project }}"
        envSlug: "{{ .Values.parameters.infisical.env }}"
        secretsPath: "/"

  managedKubeSecretReferences:
    - secretName: registry-secret
      secretType: kubernetes.io/dockerconfigjson
      secretNamespace: "{{ .Release.Namespace }}"
      creationPolicy: Owner
      template:
        data:
          .dockerconfigjson: "{{`{{ .DOCKERCONFIGJSON.Value }}`}}"
