<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Imparsable.Parsing\Imparsable.Parsing.csproj"/>
        <ProjectReference Include="..\Imparsable.Parsing.SourceGenerators\Imparsable.Parsing.SourceGenerators.csproj" OutputItemType="Analyzer"/>
    </ItemGroup>

</Project>
