apiVersion: "v2"
name: "imparsable"
version: "1.0.0"
kubeVersion: ">= 1.18.0-0"
description: "The Imparsable Helm chart"
type: "application"
keywords:
  - "aspire"
  - "kubernetes"
appVersion: "1.0.0"
deprecated: false
